name: adguard_logger
description: "AdGuard Logger"
version: 1.0.4
homepage: 'https://example.org'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  archive: ^4.0.0
  async: ^2.11.0
  collection: ^1.18.0
  http: ^1.2.2
  idb_shim: ^2.6.1+7
  intl: ^0.20.2
  meta: ^1.12.0
  path: ^1.9.0
  rxdart: ^0.28.0
  stack_trace: ^1.11.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
