name: adguard_logger
description: "AdGuard Logger"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  archive: ^3.6.1
  async: ^2.11.0
  collection: ^1.18.0
  http: ^1.2.2
  idb_shim: ^2.6.0+5
  intl: ^0.19.0
  meta: ^1.12.0
  path_provider: ^2.1.4
  path: ^1.9.1
  rxdart: ^0.28.0
  stack_trace: ^1.12.0
  uuid: ^4.5.1

